matrix:
  include:
  - os: linux
    language: minimal
    services:
      - docker
    before_install:
      - docker pull fritzing/build:xenial
    script:
      - docker/build-linux.sh

  - os: osx
    language: cpp
    osx_image: xcode10.2
    cache:
      directories:
        ../libgit2/build

    addons:
      homebrew:
        packages:
          - qt5

    before_install:
      - mkdir -p ../libgit2/build
      - wget -q -O - https://github.com/libgit2/libgit2/archive/v0.28.1.tar.gz | tar xz && mv libgit2-0.28.1/* ../libgit2/
      - (cd ../libgit2/build && cmake -D BUILD_SHARED_LIBS=OFF .. && cmake --build .)
      - (cd src/lib && wget -q -O - https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2 | tar xj)
      - xcrun -sdk macosx --show-sdk-path
    script:
      - tools/deploy_fritzing_mac.sh

  - os: osx
    language: objective-c
    osx_image: xcode10.1
    cache:
      directories:
        ../libgit2/build

    addons:
      homebrew:
        packages:
          - qt5

    before_install:
      - mkdir -p ../libgit2/build
      - wget -q -O - https://github.com/libgit2/libgit2/archive/v0.28.1.tar.gz | tar xz && mv libgit2-0.28.1/* ../libgit2/
      - (cd ../libgit2/build && cmake -D BUILD_SHARED_LIBS=OFF .. && cmake --build .)
      - (cd src/lib && wget -q -O - https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2 | tar xj)
      - xcrun -sdk macosx --show-sdk-path
    script:
      - tools/deploy_fritzing_mac.sh

  - os: windows
    language: cpp
    cache:
      directories:
        - /c/Qt
    before_install:
      - ./tools/scripts/win_fetch_dependencies.sh

    script:
        - tools/build-windows.bat
